models.py
from django.db import models
from geriatrics.models import Admission

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name

class Document(models.Model):
    admission = models.ForeignKey(Admission, on_delete=models.CASCADE)
    date = models.DateField(auto_now=False, null=False, blank=False)
    name = models.CharField(max_length=200, db_index=True)
    category = models.ForeignKey(Category, related_name='documents',
                                 on_delete=models.CASCADE)
    document = models.ImageField(upload_to='documents/%Y/%m/%d/', blank=True)
    remarks = models.TextField(blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'document'
    
    def __str__(self):
        return f'{self.name} of {self.admission} on {self.date}'

views.py
from django.shortcuts import render

# Create your views here.

templates/scanned_docs/includes/scanned_docs.html
<h4 class="text-center">Scanned Documents</h4>
{% if admission.document_set.all %}
<div
  id="carouselExampleControls"
  class="carousel slide carousel-fade carousel-dark"
  data-mdb-ride="carousel"
>
  <div class="carousel-inner">
    {% for document in admission.document_set.all %}
      {% if forloop.first %}
        <div class="carousel-item active">
          <div class="text-center">
            <p><strong>Category: </strong>{{ document.category }}</p>
            <p><strong>Name: </strong>{{ document.name }}</p>
            <p><strong>Date: </strong>{{ document.date }}</p>
          </div>
          <a href="{{ document.document.url }}">
            <img
            src="{{ document.document.url }}"
            class="d-block w-100"
            alt="..."
            />
          </a>
          <div class="carousel-caption d-none d-md-block">
            <h5>Remarks:</h5>
            <p>{{ document.remarks }}</p>
          </div>
        </div>
      {% else %}
        <div class="carousel-item">
          <div class="text-center">
            <p><strong>Category: </strong>{{ document.category }}</p>
            <p><strong>Name: </strong>{{ document.name }}</p>
            <p><strong>Date: </strong>{{ document.date }}</p>
          </div>
          <a href="{{ document.document.url }}">
            <img
            src="{{ document.document.url }}"
            class="d-block w-100"
            alt="..."
            />
          </a>
          <div class="carousel-caption d-none d-md-block">
            <h5>Remarks:</h5>
            <p>{{ document.remarks }}</p>
          </div>
        </div>  
      {% endif %}
    {% endfor %}
  
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-mdb-target="#carouselExampleControls"
    data-mdb-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-mdb-target="#carouselExampleControls"
    data-mdb-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% else %}
  <div class="alert alert-dismissible alert-info fade show">
    <button type="button" class="close">&times;</button>
    <h4 class="alert-heading">Heads up!</h4>
    <p class="mb-0">No scanned documents to show. <a href="{% url 'scanned_docs_admin:index' %}" class="alert-link">Create</a> one now.</p>
  </div>
{% endif %}